#!/usr/bin/env bash

# Extract required fields using jq
jq -r '
  .name,
  .height,
  .weight,
  .types[0].type.name
' data.json | awk '
NR==1 { name=$0 }
NR==2 { height=$0 / 10 }
NR==3 { weight=$0 }
NR==4 { type=$0 }
END {
  printf "%s is of type %s, weighs %skg, and is %.1fm tall.\n",
         toupper(substr(name,1,1)) substr(name,2),
         toupper(substr(type,1,1)) substr(type,2),
         weight,
         height
}'
